config/routes.rb
Rails.application.routes.draw do
  # resources sets up crud paths for the resource
  resources :reviews do 
    resources :comments
    resource :bookmark
  end

  resources :users

  resource :session

  # root of the whole site is the reviews index
	root "reviews#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :body, presence: true

  profanity_filter :body, :method => 'hollow'
end

app/models/review.rb
class Review < ApplicationRecord

    # add an association that has a 1-to-many relationship
    has_many :comments

    # add an association for bookmarks
    has_many :bookmarks

    # Add an association to a user
    belongs_to :user

    # Geocoder
    geocoded_by :address
    after_validation :geocode

    # Check model input
    validates :title, presence: true
    validates :body, length: { minimum: 10 }
    validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :restaurant, presence: true
    validates :address, presence: true

    def to_param
        id.to_s + "-" + title.parameterize
    end  

end

app/models/user.rb
class User < ApplicationRecord

    has_many :reviews
    has_many :comments
    has_many :bookmarks

    # Run has_secure_password
    has_secure_password

    # Validate username
    validates :username, presence: true, uniqueness: true

    # Validates email
    validates :email, presence: true, uniqueness: true

    # We dont need to validate real_name becuase it is an optional field

    def to_param
        username
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    #before any page load find the current user
    before_action :find_current_user

    # Methods to use in views
    helper_method :is_logged_in?

    def find_current_user
        if is_logged_in? 
            @current_user = User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    #check login status
    def check_login
        unless is_logged_in?
            redirect_to new_session_path
        end
    end

    # is a user logged in
    def is_logged_in?

        session[:user_id].present?

    end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    before_action :check_login

    def create
        @review = Review.find(params[:review_id])

        @bookmark = @review.bookmarks.new
        @bookmark.user = @current_user

        @bookmark.save

        redirect_to review_path(@review)

    end

    def destroy
        @review = Review.find(params[:review_id])

        @review.bookmarks.where(user: @current_user).delete_all

        redirect_to review_path(@review)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        # What review did we leave a comment on?
        # We get the review id because we nested comments in the routes file
        @review = Review.find(params[:review_id])

        # the new comment is to be added to the comments field in the reviews db table
        @comment = @review.comments.new(params.require(:comment).permit(:body))

        #save the Comment to the User
        @comment.user = @current_user

        # save the comment
        @comment.save

        # go back to the review page
        redirect_to review_path(@review)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


    # check if logged in
    before_action :check_login, except: [:index, :show]

    # list all of the reviews
    def index

        @price = params[:price]
        @cuisine = params[:cuisine]
        @location = params[:location]
    
        #start with all reviews
        @reviews = Review.all

        #filtering by price
        if @price.present?
            @reviews = @reviews.where(price: @price)
        end

        #filter by cuisine
        if @cuisine.present?
            @reviews = @reviews.where(cuisine: @cusine)
        end

        #filter near Location
        if @location.present?
            # return all reviews that are in a 1 mile radius of the search term
            @reviews = @reviews.near(@location, 1)
        end

    end

    # define a new review
    def create
        # take info from form and add to model
        @review = Review.new(form_params)

        # Save Review to user
        @review.user = @current_user


        # if the model passes validation
        if @review.save
            # redirect to the homepage
            redirect_to root_path
        else
            #otherwise show the new view
            render "new"
        end
    end

    # create the new review in the database
    def new
        # Handle new page
        @review = Review.new
    end

    # show the review based on the id in the URL
    def show
        # the individual review page
        @review = Review.find(params[:id])
    end

    # remove the review from he database
    def destroy
        # find the individual review
        @review = Review.find(params[:id])
        
        if @review.user == @current_user
            # destroy it if they have access
            @review.destroy
        end
        # redirect to homepage
        redirect_to root_path
    end

    # edit a review - you would only want this visible to administrators
    def edit 
        # find the review to edit
        @review = Review.find(params[:id])
        
        if @review.user != @current_user
            redirect_to root_path
        end
    end

    # update the edited review in the database
    def update 
        # find review
        @review = Review.find(params[:id])
        
        if @review.user != @current_user
            redirect_to root_path
        else
            # update with new info
            if @review.update(form_params)
                # redirect to somewhere new
                redirect_to review_path(@review)
            else 
                render "edit"
            end
        end
    end

    def form_params
        params.require(:review).permit(:title, :address, :restaurant, :body, :score, :ambience, :price, :cuisine)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        # log in form
    end

    def create
        # try to log in
        # get session params from the form
        @form_data = params.require(:session)
        # pull out the username and password from form data
        @username = @form_data[:username]
        @password = @form_data[:password]
        
        # lets check the user is who they say they are
        @user = User.find_by(username: @username).try(:authenticate, @password)

        # if user is valid
        if @user

            # save the user to that users session
            session[:user_id] = @user.id

            # go to homepage
            redirect_to root_path
        else
            # rerender login form
            render "new"
        end  
    end

    def destroy
        # log out
        # remove the session completly
        reset_session
        # redirect to log in
        redirect_to new_session_path
    end

    

end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show

        @user = User.find_by(params[:username])

    end

    def new
        # a form for adding a new user
        @user = User.new
    end

    def create
        # take the form params
        # create a new user
        @user = User.new(form_params)
        # if its valid and it saves, go to the users index
        # if not, see the form with errors
        if @user.save
            # Save the session with the user
            session[:user_id] = @user.id

            redirect_to users_path
        else
            render "new"
        end
    end

    def form_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title  %> - Bien Revies – Bien reviews the best restaurants in the world</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
          <% end %>
        </h1>
      </nav>

      <nav>
        
        <% if is_logged_in? %>
          <%= @current_user.username %>
          <%= link_to "Log Out", session_path, method: :delete %>
          <%= link_to "Add a Review", new_review_path %>
        <% else %>
          <%= link_to "Sign Up", new_user_path %>
          <%= link_to "Log In", new_session_path %>
        <% end %>
        
      </nav>
     
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2022 @ James Wood
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f|%>
  <%= f.input :title %>
  <%= f.input :restaurant %>
  <%= f.input :address %>
  <%= f.input :body %>
  <%= f.input :cuisine %>
  <%= f.input :price %>
  <%= f.input :score %>
  <%= f.input :ambience %>

  <%= f.button :submit %>
<% end %>

app/views/reviews/edit.html.erb
<% content_for :page_title, "Edit " + @review.title %>

<h3>Edit your Restaurant Review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
    <%= active_link_to "All Restaurants", root_path, active: { price: nil, cuisine: nil, location: nil } %>
    <div>
    <%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
    <%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 } %>
    <%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 }  %>
    </div>
    <div>
    <%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price), active: { cuisine: "Indian" }  %>
    </div>

    <form action="/">
        <input type="text" name="location" placeholder="search location..." value="<%= @location %>">
        <input type="hidden" name="price" value="<%= @price %>">
        <input type="hidden" name="cuisine" value="<%= @cuisine %>">
    </form>

</nav>

<% @reviews.each do |review| %>

	<div class="review">
        <%= link_to review_path(review) do %>
            <h2><%= review.title %></h2>
            <p>
                <%= review.cuisine %> - 
                <%= pluralize review.comments.count, "comment" %>
            </p>

        <% end %>
    </div>

<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add Your New Restaurant Review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>

<% if is_logged_in? %>

   <p>

        <% if @review.bookmarks.where(user: @current_user).any? %>
            <%= link_to "UnBookmark", review_bookmark_path(@review), method: :delete %>
        <% else %>
            <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
        <% end %>
   </p>

<% end %>

<h3>Bookmarked by...</h3>
<ul>
    <% @review.bookmarks.each do |bookmark| %>
        <li><%= bookmark.user.username %></li>
    <% end %>
</ul>




<div class="score">
    <p><%= @review.score %> / 10</p>
</div>

<div class="user">
    <p>Posted By: 
        <%if @review.user.present? %>
            <%= link_to @review.user.username, user_path(@review.user) %>
        <%else%>
            Anonymous
        <%end%>
    </p>
</div>

<% if @review.ambience.present? %>
    <div class="ambience">
        <p><%= @review.ambience %></p> 
    </div>
<% end %>

<% if @review.price.present? %>
    <div class="price">
        <p><%= @review.price %></p> 
    </div>
<% end %>

<% if @review.cuisine.present? %>
    <div class="cuisine">
        <p><%= @review.cuisine %></p> 
    </div>
<% end %>

<div class="body">
    <%= simple_format @review.body %>
</div>

<% if @review.user == @current_user %>
<div class="actions">
    <%= link_to "Edit this Review", edit_review_path(@review) %>
    <%= link_to "Delete Review", review_path(@review), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<% end %>

<h3>Comments</h3>

<% @review.comments.order('created_at desc').each do |comment| %>
    <div class="comment">
        <%# <%= simple_format ProfanityFilter::Base.clean(comment.body, 'hollow') %>
        <%# moved profanity filter to the model %>
        <%= simple_format comment.body %>
        
        <p class="posted">Posted By: 
        <% if comment.user.present? %>
            <%= link_to comment.user.username, user_path(comment.user) %>
        <% else %>
            Anonymous
        <% end %>
        </p>

        <p class="posted">Posted at: <%= time_ago_in_words comment.created_at %> ago</p>
    </div>
<% end %>


<h3>Add a comment</h3>

<%= simple_form_for [@review, Comment.new] do |f| %>
    <%= f.input :body, label: "Type your comment here" %>
    <%= f.button :submit, "Comment" %>
<% end %>

app/views/users/index.html.erb
<h2>All Users</h2>

<% @users.each do |user| %>

    <p><%= user.username %> (<%= user.email %>)</p>
    
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= simple_form_for @user do |f| %>

    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.button :submit, "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<p>Their email is <%= @user.email %></p>